=== RusPosevkin/xsl-school-homework/1/shop.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
annotation - корневой элемент
	section - список новостей, может быть от 0 до бесконечности
	section@id - обязательный атрибут числового типа
    внутри section разрешены
	1. только один title, без вложений
    2. Один и более para, без вложений
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="announcements">
		<xs:annotation>
			<xs:documentation>Список новостей платежных форм</xs:documentation>
		</xs:annotation>
		<xs:complexType>
		  <xs:sequence>
			<xs:element name="section" minOccurs="0" maxOccurs="unbounded">
			   <xs:annotation>
				<xs:documentation>Да, новостей может и не быть</xs:documentation>
			  </xs:annotation>
			  <xs:complexType>
				<xs:sequence>
				  <xs:element type="xs:string" name="title" maxOccurs="1" minOccurs="1">
					  <xs:annotation>
						<xs:documentation>Заголовок обязателен для каждого объявления</xs:documentation>
					</xs:annotation>
				  </xs:element>
				  <xs:element type="xs:string" name="para" maxOccurs="unbounded" minOccurs="1">
					   <xs:annotation>
						<xs:documentation>Текст объявления тоже должен быть, хотя бы в одном теге para</xs:documentation>
					</xs:annotation>
				  </xs:element>
				</xs:sequence>
				<xs:attribute type="xs:byte" name="id" use="required"/>
			  </xs:complexType>
			</xs:element>
		  </xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== RusPosevkin/xsl-school-homework/1/shop.xml
<?xml version="1.0" encoding="UTF-8"?>
<announcements xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="shop.xsd">
	<section id="1">
		<title>Яндекс.Деньги разрешили передавать идентификацию по наследству</title>
		<para>Теперь пользователи, у которых есть хотя бы один идентифицированный кошелек, могут идентифицировать остальные — не выходя из дома. Пользователи открывают несколько кошельков для разных целей. Например, так удобнее отслеживать поступление денег по каждой благотворительной акции. Кроме того, если меняется адрес на Яндекс.Почте, проще создать новый кошелек под новым логином. Теперь идентифицировать «запасные» счета можно в несколько кликов — сервис позволяет скопировать паспортные данные из одного кошелька в другой.</para>
	</section>
	<section id="2">
		<title>Яндекс.Деньги покажут штрафы ГИБДД</title>
		<para>В Яндекс.Деньгах появилась новая услуга — проверка задолженностей по штрафам ГИБДД. Теперь любой пользователь рунета может получить информацию о своих штрафах и сразу оплатить каждый из них (даже если у него нет электронного кошелька).</para>
		<para>Для проверки понадобится только номер водительского удостоверения и свидетельства о регистрации автомобиля. Поиск по этим данным ведется в Государственной информационной системе о государственных и муниципальных платежах (ГИС ГМП) среди штрафов, выставленных с лета 2013 года. В результате пользователь увидит, когда было выписано постановление, дату, до которой нужно погасить задолженность, и сумму штрафа.</para>
	</section>
	<section id="3">
		<title>Яндекс.Деньги включили Кассу всем пользователям Nethouse</title>
		<para>Теперь пользователи конструктора сайтов Nethouse могут принимать онлайн-платежи через Кассу от Яндекс.Денег.</para>
		<para>На базе Nethouse создано 320 тысяч сайтов, около 40% из них — интернет-магазины.</para>
		<para>Теперь каждый из них может предложить посетителям выбрать удобный способ оплаты: с электронных кошельков Яндекс.Денег и Webmoney, банковских карт Visa и Visa Electron, MasterCard и Maestro, а также наличными через терминалы и салоны связи (всего более 170 тыс точек приема оплаты).</para>
	</section>
</announcements>
